title: Your Site Title
description: A brief description of your site
baseurl: "" # the subpath of your site, e.g., "/blog" if your site is at "yourusername.github.io/blog"
url: "https://yourusername.github.io" # the base hostname & protocol for your site

